# Generated by Django 4.2.7 on 2023-11-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row1', models.CharField(max_length=9)),
                ('row2', models.CharField(max_length=9)),
                ('row3', models.CharField(max_length=9)),
                ('row4', models.CharField(max_length=9)),
                ('row5', models.CharField(max_length=9)),
                ('row6', models.CharField(max_length=9)),
                ('row7', models.CharField(max_length=9)),
                ('row8', models.CharField(max_length=9)),
                ('row9', models.CharField(max_length=9)),
            ],
        ),
    ]
