# Generated by Django 4.2.7 on 2023-11-12 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='row1',
        ),
        migrations.RemoveField(
            model_name='react',
            name='row2',
        ),
        migrations.RemoveField(
            model_name='react',
            name='row3',
        ),
        migrations.RemoveField(
            model_name='react',
            name='row4',
        ),
        migrations.RemoveField(
            model_name='react',
            name='row5',
        ),
        migrations.RemoveField(
            model_name='react',
            name='row6',
        ),
        migrations.RemoveField(
            model_name='react',
            name='row7',
        ),
        migrations.RemoveField(
            model_name='react',
            name='row8',
        ),
        migrations.RemoveField(
            model_name='react',
            name='row9',
        ),
    ]
