# Generated by Django 4.2.7 on 2023-11-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0002_remove_react_row1_remove_react_row2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='row1',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='react',
            name='row2',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='react',
            name='row3',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
