# Generated by Django 4.2.7 on 2023-11-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0003_react_row1_react_row2_react_row3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='row2',
        ),
        migrations.RemoveField(
            model_name='react',
            name='row3',
        ),
        migrations.AlterField(
            model_name='react',
            name='row1',
            field=models.CharField(max_length=5),
        ),
    ]
