# Generated by Django 4.2.7 on 2023-11-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0004_remove_react_row2_remove_react_row3_alter_react_row1'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='row2',
            field=models.CharField(default=0, max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='react',
            name='row3',
            field=models.CharField(default=0, max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='react',
            name='row4',
            field=models.CharField(default=0, max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='react',
            name='row5',
            field=models.CharField(default=0, max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='react',
            name='row6',
            field=models.CharField(default=0, max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='react',
            name='row7',
            field=models.CharField(default=0, max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='react',
            name='row8',
            field=models.CharField(default=0, max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='react',
            name='row9',
            field=models.CharField(default=0, max_length=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='react',
            name='row1',
            field=models.CharField(max_length=18),
        ),
    ]
